# Generated by Django 5.0.6 on 2024-08-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='pic',
            field=models.ImageField(default='de.jpg', upload_to=''),
        ),
    ]
