# Generated by Django 5.0.6 on 2024-08-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
