# Generated by Django 5.0.6 on 2024-08-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skills_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='ud',
            field=models.IntegerField(default=0),
        ),
    ]
