# Generated by Django 5.0.6 on 2024-08-31 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='pic',
            field=models.ImageField(default='user.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
